### ISSUE TITLE
Update Proposals Modal

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/bufficorn#18]
Remove Basics and Advanced headings and only provide the following options:

- Signal Request (Initiate Vote)
- ERC-20 Token Transfer (Fund Company)
- DAO Token Swap (Become Partner)
- DAO Token Request (Add Partner)

Use the names in parentheses

**Comment by skuhlmann** [comment]
Might need to update the macros package to allow us to pass actions buttons to the proposal list like the header prop.

**Comment by skuhlmann** [comment]
https://github.com/0xBootleggers/bufficorn/pull/29
