### ISSUE TITLE
Replace Footer

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/bufficorn#28]
Add Built by Bootleggers footer

**Comment by skuhlmann** [comment]
When this package gets updated you are going to add the custom footer as new prop on <DHLayout />. It's called footer and it must be a react node.

```tsx
    <DHLayout
      pathname={location.pathname}
      navLinks={[
        { label: "Home", href: `/` },
        { label: "Proposals", href: `${routePath}/proposals` },
        { label: "Partners", href: `${routePath}/members` },
        { label: "Treasury", href: `${routePath}/safes` },
        { label: "Settings", href: `${routePath}/settings` },
      ]}
      leftNav={dao && <HeaderAvatar name={dao.name} imgUrl={dao.avatarImg} />}
      footer={<SomeCustomFooter />}
    >
```

**Comment by earth2travis** [comment]
Cannot figure out why this typeface is jacked up

The one on the top is how it is supposed to be:

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/f648466d-279e-4653-87c6-7fe0c8dbdbbe)

The one on the bottom is how it is rendering

The correct font is in the CSS:

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/a413c25d-2e3a-4459-b94c-d4612ee177be)

**Comment by earth2travis** [comment]
Kept it simple an just added the jug with a link to our site

<img width="1181" alt="image" src="https://github.com/0xBootleggers/bufficorn/assets/522182/5d5ebd3a-5762-47eb-a645-31e18f0df81d">

**Comment by earth2travis** [comment]
https://github.com/0xBootleggers/bufficorn/pull/55

**Comment by earth2travis** [comment]
Good call on Windsong Medium. Played with the weights and am not even importing that variation. IDK

**Comment by earth2travis** [comment]
https://github.com/0xBootleggers/bufficorn/pull/56

**Comment by earth2travis** [comment]
Footer changes did not role to production. Wonder if it has something todo with this in Vercel:

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/d01f65fb-0f4a-4074-8740-0c98edef993c)

I also may have somehow duplicated the `main` branch

**Comment by earth2travis** [comment]
May not have pushed these updates previously 🤷 
https://github.com/0xBootleggers/bufficorn/pull/62

**Comment by earth2travis** [comment]
![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/6e30e0c6-4a2f-4d87-8480-aa3a3a190e66)
