### ISSUE TITLE
Remove Offering from Proposals

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/bufficorn#34]
Lego package prop offering always showing on dao that doesn't have one

**Comment by skuhlmann** [comment]
I think this was fixed in a previous update. But either way it's not actually adding any offering value so not stopping any functionality.

**Comment by earth2travis** [comment]
Confirmed there is no offering field:

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/6d9c5d93-bd46-477f-b680-d4ddbe245fbe)
