### ISSUE TITLE
Fix Become Partner Token Address Error

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/bufficorn#40]
On Become Partner form adding the following 

`0x65e1738344EB68c7e2f4279aD9E1f7c253A09911` 

in the Token Address field starts loading data and then goes to the white screen of death

![white-screen](https://user-images.githubusercontent.com/522182/239412158-896b1bc0-584a-42d5-b23d-380979aa7acc.png)

http://localhost:5173/#/molochv3/0x64/0x8577c1a3caedd9a6bfa431176a9b94474cdffd9c/new-proposal?formLego=BECOME_PARTNER

**Comment by earth2travis** [comment]
I also updated this one to Partner Proposal and it is not displayed:

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/6d54ce24-9770-446d-a8f2-29ba1cef1b6c)

from `forms.ts`

```ts
  ADD_PARTNER: {
    id: 'ADD_PARTNER',
    title: 'Add Partner',
    subtitle: 'Partner Proposal',
    description: 'Send BVSTK or BVSTK-LOOT tokens.',
    tx: TX.ISSUE,
    requiredFields: {
      title: true,
      description: true,
      sharesRequested: true,
      lootRequested: true,
      recipient: true,
    },
```

**Comment by skuhlmann** [comment]
Requires a fix in the tribute input package

**Comment by earth2travis** [comment]
Replaced ability to paste address in the field with a drop-down token list

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/e7288e11-6c62-48ca-9d09-57f0a6ae798b)

**Comment by earth2travis** [comment]
https://github.com/0xBootleggers/bufficorn/issues/47
