### ISSUE TITLE
Fix Label Overrides

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/bufficorn#44]
Not able to update the following with the spread operator label override:

## [FUND_COMPANY](https://bison-narwhal.vercel.app/#/molochv3/0x64/0x8577c1a3caedd9a6bfa431176a9b94474cdffd9c/new-proposal?formLego=FUND_COMPANY)

FIELD.REQUEST_TOKEN,

{ ...FIELD.REQUEST_TOKEN, label: 'ERC-20 Tokens' },

## [BECOME_PARTNER](https://bison-narwhal.vercel.app/#/molochv3/0x64/0x8577c1a3caedd9a6bfa431176a9b94474cdffd9c/new-proposal?formLego=BECOME_PARTNER)

FIELD.TRIBUTE,

{ ...FIELD.TRIBUTE, label: 'Tribute Token Address' },

{ ...FIELD.TRIBUTE, label: 'Tribute Token Amount' },

It appears these labels are hard coded in the package

**Comment by skuhlmann** [comment]
Tribute field has 2 field labels so we have to hard code it in this instance.

This one feels super nick picky, but I'll add the word Tribute to each label.

**Comment by earth2travis** [comment]
Fund Company

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/ed471524-8887-43db-ab05-1a2597e82cf2)

Become Partner

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/682ac437-4184-4e8c-924b-1836e26563b2)
