### ISSUE TITLE
Fix Max Amount Button Overflow

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/bufficorn#45]
Max amount should be limited to 2 decimals 🤷 

![Image](https://user-images.githubusercontent.com/522182/239593152-fd002e45-9e71-4c18-a14b-89586fe9041e.png)

**Comment by skuhlmann** [comment]
@earth2travis need you to test this when the current pr is merged.

**Comment by earth2travis** [comment]
![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/e70e6b74-88d4-4b29-807d-4762c12587f5)

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/c45ebcf8-e19f-44d0-8bf1-ab79efa470d8)

This looks good on a local version of `develop`

**Comment by earth2travis** [comment]
It appears we are limiting the Max button to six decimal places. That works well. QA approved

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/8d28eb05-437c-4915-af00-bb15675d59a5)

**Comment by earth2travis** [comment]
@skuhlmann noticed this is still an issue on the FUND_COMPANY form:

http://localhost:5173/#/molochv3/0x64/0x8577c1a3caedd9a6bfa431176a9b94474cdffd9c/new-proposal?formLego=FUND_COMPANY

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/4980e33c-0b93-41e0-b873-adbfa19f18bc)

**Comment by earth2travis** [comment]
### FUND_COMPANY

![max-button](https://hackmd.io/_uploads/HJSBzP0Bn.png)

- Max button is still breaking
