### ISSUE TITLE
Limit Tribute Tokens on Become Partner Form

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/bufficorn#47]
https://bison-narwhal.vercel.app/#/molochv3/0x64/0x8577c1a3caedd9a6bfa431176a9b94474cdffd9c/new-proposal?formLego=BECOME_PARTNER

Replace Token Address field:

![Image](https://user-images.githubusercontent.com/522182/239610939-a5c5e9eb-0bb1-4f74-a36f-baf83fee6e30.png)

With select similar to: 

![Image](https://user-images.githubusercontent.com/522182/239611091-7a070641-9576-434c-a5a9-68623b99de77.png)

Limit tribute tokens DAI, USDC, SPORK

**Comment by skuhlmann** [comment]
@earth2travis Can you grab these token addresses on polygon?

and select 3 for us to use on gnosis chain?

**Comment by earth2travis** [comment]
@skuhlmann 

## Polygon

- [DAI](https://polygonscan.com/token/0x8f3cf7ad23cd3cadbd9735aff958023239c6a063): `0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063`
- [USDC](https://polygonscan.com/token/0x2791bca1f2de4661ed88a30c99a7a9449aa84174): `0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174`
- [SPORK](https://polygonscan.com/token/0x9ca6a77c8b38159fd2da9bd25bc3e259c33f5e39): `0x9CA6a77C8B38159fd2dA9Bd25bc3E259C33F5E39`

## Gnosis Chain

- [WXDAI](https://blockscout.com/xdai/mainnet/address/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d): `0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d`
- [USDC](https://blockscout.com/xdai/mainnet/address/0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83): `0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83`
- [SPICE](https://blockscout.com/xdai/mainnet/address/0x65e1738344EB68c7e2f4279aD9E1f7c253A09911): `0x65e1738344EB68c7e2f4279aD9E1f7c253A09911`

**Comment by skuhlmann** [comment]
@earth2travis 

pr here:
https://github.com/0xBootleggers/bufficorn/pull/53

we will configure the token list in the targetDao.ts file like this:

```ts
export const TARGET_DAO: {
  [key: string]: {
    ADDRESS: string;
    SAFE_ADDRESS: string;
    CHAIN_ID: ValidNetwork;
    TRIBUTE_TOKENS: OptionType[];
  };
} = {
  "0x8577c1a3caedd9a6bfa431176a9b94474cdffd9c": {
    ADDRESS: "0x8577c1a3caedd9a6bfa431176a9b94474cdffd9c",
    SAFE_ADDRESS: "0xaaa9ffe13a324676a0ff899cf21f09f56e166c6b",
    CHAIN_ID: "0x64",
    TRIBUTE_TOKENS: [
      {
        name: "WXDAI",
        value: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d",
      },
      {
        name: "USDC",
        value: "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83",
      },
      {
        name: "SPICE",
        value: "0x65e1738344EB68c7e2f4279aD9E1f7c253A09911",
      },
    ],
  },
};
```

**Comment by earth2travis** [comment]
@skuhlmann tested all three tokens all the way to execution

![Image](https://github.com/0xBootleggers/bufficorn/assets/522182/d038114f-bb90-4a07-9f42-19fe3bf5856f)
